name: Unit test for Fexios
on:
  push:
    branches: [master, dev, actions]
  pull_request:
    branches: [master, dev, actions]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Test on multiple Node.js versions that support fetch
    strategy:
      matrix:
        node-version: ['16.15.0', '18', 'lts/*', 'latest']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node Version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run build
        run: |
          npm run build

      - name: Run tests
        run: |
          npm run test
